### ISSUE TITLE
 class java.time.ZonedDateTime cannot be cast to class java.sql.Timestamp

### ISSUE THREAD

**Issue by kamil94131** [liquibase/liquibase-neo4j#314] opened 2023-02-06 01:45 UTC
Neo4jChangelogHistoryService.java, line 435: expects Timestamp, but got ZonedDateTime

Dependencies:

- liquibase-core: 4.19.0
- liquibase-neo4j: 4.19.0
- neo4j-jdbc-bolt: 5.0.0

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: java.lang.ClassCastException: class java.time.ZonedDateTime cannot be cast to class java.sql.Timestamp (java.time.ZonedDateTime is in module java.base of loader 'bootstrap'; java.sql.Timestamp is in module java.sql of loader 'platform')
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.2.jar:3.0.2]
	at com.company.BaseApplication.main(BaseApplication.java:19) ~[classes/:na]
Caused by: liquibase.exception.LiquibaseException: java.lang.ClassCastException: class java.time.ZonedDateTime cannot be cast to class java.sql.Timestamp (java.time.ZonedDateTime is in module java.base of loader 'bootstrap'; java.sql.Timestamp is in module java.sql of loader 'platform')
	at liquibase.Liquibase.runInScope(Liquibase.java:2436) ~[liquibase-core-4.19.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:237) ~[liquibase-core-4.19.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:222) ~[liquibase-core-4.19.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:328) ~[liquibase-core-4.19.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:283) ~[liquibase-core-4.19.0.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747) ~[spring-beans-6.0.4.jar:6.0.4]
	... 16 common frames omitted
Caused by: java.lang.ClassCastException: class java.time.ZonedDateTime cannot be cast to class java.sql.Timestamp (java.time.ZonedDateTime is in module java.base of loader 'bootstrap'; java.sql.Timestamp is in module java.sql of loader 'platform')
	at liquibase.ext.neo4j.changelog.Neo4jChangelogHistoryService.mapRanChangeSet(Neo4jChangelogHistoryService.java:435) ~[liquibase-neo4j-4.19.0.jar:4.19.0]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at liquibase.ext.neo4j.changelog.Neo4jChangelogHistoryService.mapRanChangeSets(Neo4jChangelogHistoryService.java:206) ~[liquibase-neo4j-4.19.0.jar:4.19.0]
	at liquibase.ext.neo4j.changelog.Neo4jChangelogHistoryService.getRanChangeSets(Neo4jChangelogHistoryService.java:88) ~[liquibase-neo4j-4.19.0.jar:4.19.0]
	at liquibase.changelog.AbstractChangeLogHistoryService.upgradeChecksums(AbstractChangeLogHistoryService.java:68) ~[liquibase-core-4.19.0.jar:na]
	at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1939) ~[liquibase-core-4.19.0.jar:na]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:251) ~[liquibase-core-4.19.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.19.0.jar:na]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.19.0.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.19.0.jar:na]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.19.0.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:2431) ~[liquibase-core-4.19.0.jar:na]
	... 22 common frames omitted

```

**Comment by fbiville** [comment] 2023-02-13 12:01
Thanks for the report, let me look into it now.

**Comment by fbiville** [comment] 2023-02-13 12:05
First note: you do not need `neo4j-jdbc-bolt` anymore, since 4.19.0 has a brand new built-in JDBC connector.
You can drop that dependency if you do not need it anywhere else.

**Comment by chudok** [comment] 2023-02-13 12:07
Hello! I have the same problem.

**Comment by fbiville** [comment] 2023-02-13 12:12
Can @chudok or @kamil94131 share a minimal Liquibase change log that exhibits the issue? That would help a lot!

**Comment by fbiville** [comment] 2023-02-13 12:27
I tried to reproduce it by running a simple change log with Liquibase Neo4j 4.18.01 and re-running it with 4.19.0 to no avail (all using Liquibase core 4.19.0).
I am unfortunately going to need more information before proceeding.
The error is pretty clear, it's rather the context in which it occurs that I need to understand.

**Comment by chudok** [comment] 2023-02-14 11:00
Thank you for your answer. There's my code:
```
new Liquibase("/example/install.xml",
                new DirectoryResourceAccessor("/tmp"),
                new JdbcConnection(DriverManager.getConnection(conf.getDbUrl(), creds.getUsername(), creds.getPassword())));
```

If I don't use neo4j-jdbc-bolt then I get an error something like this "Cannot find database driver". If I add neo4j-jdbc-bolt driver, I have error about ZoneDateTime. If I downgrade version to 4.18.0 then all is ok. Current workaround looks like this:

```	
	        <dependency>
			<groupId>org.liquibase</groupId>
			<artifactId>liquibase-core</artifactId>
			<version>4.18.0</version>
		</dependency>
		<dependency>
			<groupId>org.liquibase.ext</groupId>
			<artifactId>liquibase-neo4j</artifactId>
			<version>4.18.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.neo4j.driver</groupId>
					<artifactId>neo4j-java-driver</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.neo4j</groupId>
			<artifactId>neo4j-jdbc-bolt</artifactId>
			<version>4.0.5</version>
		</dependency>
```

**Comment by fbiville** [comment] 2023-02-14 14:29
Thanks for providing the details, so it seems you're using Liquibase core's and the JDBC's APIs directly.
I'll try to reproduce that setup this week.

**Comment by fbiville** [comment] 2023-02-15 14:21
I just created https://github.com/fbiville/liquibase-neo4j-issue-314 and tried it with the fix in https://github.com/liquibase/liquibase-neo4j/pull/317 and it seems to work.

@chudok / @kamil94131 can you give it a try as well?

**Comment by chudok** [comment] 2023-02-16 09:23
I tried, but got an error...

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/12711129/219321613-f40391a3-e1cb-4b7e-aebd-439ac059de3e.png">


if using workaround, code is working
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/12711129/219323058-a88ddd4b-9333-47be-8f6a-d7711ce66e79.png">

**Comment by chudok** [comment] 2023-02-16 10:02
I added java.sql.driver file with content "liquibase.ext.neo4j.database.jdbc.Neo4jDriver" to META-INF/services. It's working for me. (get from https://www.baeldung.com/java-jdbc-loading-drivers#jdbc-4-approach)
<img width="954" alt="image" src="https://user-images.githubusercontent.com/12711129/219333335-19f73b53-7644-4319-ab3a-efb9bb769eff.png">

**Comment by fbiville** [comment] 2023-02-16 15:00
So, I think the fix works out for @chudok.
What about you @kamil94131, would you have any time to try it out in the coming days? The earlier you confirm, the earlier I can publish a release with the fix.

**Comment by fbiville** [comment] 2023-02-16 15:50
Actually, stepping back a bit and chatting with @nvoxland made me realize (or rather: remember) that register the built-in JDBC driver is a bad idea. It is meant to be internal to Liquibase.

Registering it as in #317 is not a good idea, since it would be a global side effect, with potential repercussions outside of Liquibase.

Let me see if I can fix the `ClassCastException` directly and if that solves the problem.
Of course, not registering the driver means users will have to instantiate it themselves.

It is sadly a breaking change from 4.18.0, but explicitly instantiating `liquibase.ext.neo4j.database.jdbc.Neo4jDriver` is quite an easy workaround, which will be then documented shortly.

**Comment by fbiville** [comment] 2023-02-21 11:22
The root cause on the third-party JDBC connector is actually this one: https://github.com/neo4j-contrib/neo4j-jdbc/issues/412. Fixing it is a breaking change there.

We actually discussed with Nathan whether the extension could support both the third-party JDBC driver and the new built-in one.

After much consideration, I have come to the conclusion this is currently not a viable option.

I filed several bugs against the third-party JDBC connector and most of the fixes will be breaking changes, so they cannot be handled right now:

- https://github.com/neo4j-contrib/neo4j-jdbc/issues/377 (may be fixed in a backwards-compatible manner) -  this blocks usages of `runInTransaction=false` (think of `CALL {} IN TRANSACTIONS`
- https://github.com/neo4j-contrib/neo4j-jdbc/issues/397 (can be fined in a backwards-compatible manner)
- https://github.com/neo4j-contrib/neo4j-jdbc/issues/401 (fixing this results in a breaking change)
 - https://github.com/neo4j-contrib/neo4j-jdbc/issues/412 (fixing this results in a breaking change)

Moreover, the third-party JDBC connector is designed for general use whereas the built-in JDBC connector handles the usecase for Liquibase and Liquibase only.
The key differentiator is that Liquibase only ever uses a single connection throughout an entire execution.
As a result, the built-in JDBC connector does not need to cache the costly-to-create driver instance, it just creates one whenever a connection is requested and closes it when the connection closes.
On the other hand, the third-party JDBC connector has to deal with sharing driver instances across several connections. Since creating a driver is costly, it has to cache it at the Driver level. 
Doing this comes with a huge drawback: a JDBC Driver instance cannot be closed. As a result, the underlying native driver instance cannot be closed.

Don't get me wrong, I'm not saying the third-party JDBC connector is bad or should be avoided.
It's helped me bootstrap projects like Liquigraph and now the Neo4j extension for Liquibase pretty quickly.
However, its problem space is much bigger than the built-in one's and it comes with several drawbacks.

Going forward, here is what Liquibase/Neo4j users will have to do:

1. drop the `neo4j-jdbc` dependency
2. when using the core Java API, do not use `DriverManager.getDriver` but instantiate `liquibase.ext.neo4j.database.jdbc.Neo4jDriver` directly

Alternatively, users can stay with the 4.18.x version of the Neo4j extension for the time being, but this is not a viable long-term solution.

**Comment by fbiville** [comment] 2023-03-02 12:08
Hopefully, the new documentation will help: https://github.com/liquibase/liquibase-neo4j/pull/328.
Let me know what you think @chudok @kamil94131 (I'll merge this soon, but we can always refine the docs with subsequent PRs).

**Closed** 2023-03-02 14:07 UTC
Labels: bug
