### ISSUE TITLE
Rollback to tag

### ISSUE THREAD

**Issue by cpeluzzo** [liquibase/liquibase-neo4j#78] opened 2021-10-15 10:00 UTC
I'm trying to test if I can rollback to a tag. I'm following the example, but adding tags and a new "Movie".

OS and components:

- OS: Ubuntu 20.04.3 LTS
- Docker: neo4j:4.2.5-community
- Java: openjdk version "1.8.0_292"
- Liquibase: Liquibase Version: 4.5.0, Liquibase Community 4.5.0 by Datical
- Liquibase/lib: neo4j-jdbc-driver-4.0.5.jar, liquibase-neo4j-4.5.0.jar

Files:

- changeLog.xml

```sh
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd">

    <changeSet id="my-movie-init" author="fbiville">
        <comment>Creates a forgettable movie</comment>
        <sql>CREATE (:Movie {title: 'My Life'})</sql>
        <rollback>MATCH (n:Movie {title: 'My Life'}) DELETE n</rollback>
    </changeSet>
</databaseChangeLog>
```
- changeLog2.xml

```sh
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd">

    <changeSet id="add-new-film" author="cp">
        <comment>Creates a new movie</comment>
        <sql>CREATE (:Movie {title: 'New Movie'})</sql>
        <rollback>MATCH (n:Movie {title: 'New Movie'}) DELETE n</rollback>
    </changeSet>
</databaseChangeLog>
```

Chain of cmd's:

```sh
liquibase --url jdbc:neo4j:bolt://localhost --username neo4j --password test --changeLogFile changeLog.xml update
liquibase --url jdbc:neo4j:bolt://localhost --username neo4j --password test tag initial
liquibase --url jdbc:neo4j:bolt://localhost --username neo4j --password test --changeLogFile changeLog2.xml update
liquibase --url jdbc:neo4j:bolt://localhost --username neo4j --password test tag final
##If you try to rollback to 'initial' tag doesn't exits.
liquibase --url jdbc:neo4j:bolt://localhost --username neo4j --password test --changeLogFile changeLog2.xml rollback initial
##
##
Starting Liquibase at 10:39:00 (version 4.5.0 #52 built at 2021-09-27 16:19+0000)
Liquibase Version: 4.5.0
Liquibase Community 4.5.0 by Datical
Unexpected error running Liquibase: Could not find tag 'initial' in the database
```

If I check the DDBB in the browser, I can see:

![imagen](https://user-images.githubusercontent.com/47538962/137119337-c5bbd399-37fa-4f35-bf1a-b209e46b6ee1.png)

"initial" has lost its link "TAGS" with its "SQL". Every time a new tag is created for a new change; the previous tag loses "TAGS" link.

Maybe there is some kind of problem with the query in "mergeTag"?

https://github.com/liquibase/liquibase-neo4j/blob/cca1625a7da838c30659ae58177e8b1ee1e58035/src/main/java/liquibase/ext/neo4j/changelog/Neo4jChangelogHistoryService.java#L400

But I'm not sure about that... Maybe I'm just doing something wrong ...

Thanks,

Carlos

**Comment by fbiville** [comment] 2021-11-30 16:58
Hi, I'm looking at this this week, now that I'm back from parental leave.
Rolling back to a tag should be supported, I'll post updates soon.

**Comment by fbiville** [comment] 2021-12-02 14:59
One thing that puzzles me a bit is that you are running two distinct, separate change logs against the same instance, is that on purpose?

If you want to run change sets `"my-movie-init"` and `"add-new-film"`, one usually defines them in the same change log (either directly in the same file, or in separate files but with one file includes the other one  - see [`include`](https://docs.liquibase.com/concepts/advanced/include.html) and [`includeAll`](https://docs.liquibase.com/concepts/advanced/includeall.html)).

Your approach will work but I think this is a bit unusual.

**Comment by fbiville** [comment] 2021-12-02 15:17
Digging a little bit in the [history](https://github.com/liquibase/liquibase-neo4j/pull/2#issuecomment-765520883) of the tag implementation (pun intended), the following should _in theory_ happen when tagging (let's say the tag is called`"foo"`):

 - any change set previously tagged with `"foo"` should be untagged
 - the latest change set's tags should be untagged (a change set can only be tagged once)
 - the latest change set is then tagged with `"foo"`

**Comment by fbiville** [comment] 2021-12-02 15:56
I can reproduce the issue as well and agree with you, @cpeluzzo , that deleting the `"initial"`tag is ... surprising to say the least.

I also reproduce the issue when the two change sets are defined in the same change log. So I will definitely fix the issue in that scenario.

However, I'm not sure what tagging is supposed to do when several change logs are in the mix.
I could pick the latest change set across all persisted change logs, but that seems a bit arbitrary to me. Shouldn't the tag command be explicit about the change log is targets? I will defer to @nvoxland on that one.

**Comment by cpeluzzo** [comment] 2021-12-03 09:00
> One thing that puzzles me a bit is that you are running two distinct, separate change logs (with 1 change set each) against the same Neo4j database, is that on purpose?
 > If you want to run change sets "my-movie-init" and "add-new-film", you would typically define them in the same change log (either directly in the same file, or in separate files but with one file includes the other one - see include and includeAll).
 > Your approach will work but I think this is a bit unusual.

@fbiville You are completely right, I should have used the same file for the changelogs, or use "include" or "includeAll" to read several files. I did the tests like that too, but I have no idea right now why I decided to present the PR with two separate files... :confused:. 
Anyway, I was not my intention to put a spotlight in this particular behavior of providing 2 separate files for change logs.

**Comment by fbiville** [comment] 2021-12-03 11:14
No worries at all, something suspicious still happens even within a unified change log, so it's definitely worth reporting and investigating.
Moreover, the tagging logic is actually quite complex so I'm not entirely surprised you found holes in the current implementation, thanks a lot for that!

**Comment by fbiville** [comment] 2022-01-11 13:30
@cpeluzzo thanks for your patience. I believe your issue is fixed with https://github.com/liquibase/liquibase-neo4j/pull/103.

**Closed** 2022-01-11 14:46 UTC
Labels: bug

**Comment by fbiville** [comment] 2022-01-12 14:33
The fix is now available with https://github.com/liquibase/liquibase-neo4j/releases/tag/liquibase-neo4j-4.7.0.1
