### ISSUE TITLE
Missing validCheckSum property in __LiquibaseChangeSet nodes

### ISSUE THREAD

**Issue by katadonutskuri** [liquibase/liquibase-neo4j#92] opened 2021-12-01 20:12 UTC
Hi

I was reading (https://docs.liquibase.com/concepts/basic/changeset.html), and it seems the `validCheckSum` tag is used to bypass saved checksum. But for neo4j, that validCheckSum doesn't seem to be saved in the `__LiquibaseChangeSet` nodes.

So as a test, changing a changeset slightly fails the checksum validation despite having the validCheckSum tag.

```xml
<!-- original changeset -->
<changeSet id="..." author="...">
    <validCheckSum>289g9bc1-2ee4-5d91-b268-47cd400d96a2</validCheckSum>
    <comment>...</comment>
    <sql>
      CREATE CONSTRAINT constraint_emp_id IF NOT EXISTS ON (n:Employee) ASSERT n.eid IS UNIQUE;
      CREATE INDEX index_emp_name IF NOT EXISTS FOR (n:Employee) ON (n.name);
    </sql>
</changeSet>

<!-- modified changeset -->
<changeSet id="..." author="...">
    <validCheckSum>289g9bc1-2ee4-5d91-b268-47cd400d96a2</validCheckSum>
    <comment>...</comment>
    <sql>
      CREATE CONSTRAINT constraint_emp_id IF NOT EXISTS ON (n:Employee) ASSERT n.eid IS UNIQUE;
      <!-- CREATE INDEX index_emp_name IF NOT EXISTS FOR (n:Employee) ON (n.name); -->
    </sql>
</changeSet>
```

**Comment by fbiville** [comment] 2021-12-02 10:08
Thanks for reporting this, I was not aware of that feature.
As a result, it is currently unsupported.
I will try to get this released ASAP.

**Comment by fbiville** [comment] 2021-12-06 09:30
Hello, after re-reading what `<validChecksum />` does, I don't think it needs to be persisted in the graph, since it's already persisted on file and is used to bypass what's persisted in the database.
I also think `<validChecksum />` should work out-of-the-box, let me try to reproduce the problem you describe.

**Comment by fbiville** [comment] 2021-12-06 09:40
I cannot reproduce the issue.
Here is how I proceeded:

1. I created a simple change log:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd">

    <changeSet id="my-movie-init" author="fbiville">
        <comment>Creates a forgettable movie</comment>
        <sql>MERGE (m:Movie {title: 'My Life'})</sql>
    </changeSet>
</databaseChangeLog>
```
2. I ran it with `liquibase [...] update`
3. I changed the change set as follows:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd">

    <changeSet id="my-movie-init" author="fbiville">
        <comment>Creates a forgettable movie</comment>
        <sql>MERGE (m:Movie {title: 'My Life'}) SET m.age = 42</sql>
    </changeSet>
</databaseChangeLog>
```
4. I re-ran the CLI `liquibase [...] update` and got the following error message:
```shell
Starting Liquibase at 10:36:16 (version 4.6.2 #886 built at 2021-11-30 16:20+0000)
[...]
Unexpected error running Liquibase: Validation Failed:
     1 change sets check sum
          changelog.xml::my-movie-init::fbiville was: 8:35492f6e475cfc80a31d24d2446e3cf4 but is now: 8:93d795450e1871cedc5f387c4d31658c
```
5. I finally change the change set to:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd">

    <changeSet id="my-movie-init" author="fbiville">
        <validCheckSum>8:93d795450e1871cedc5f387c4d31658c</validCheckSum>
        <comment>Creates a forgettable movie</comment>
        <sql>MERGE (m:Movie {title: 'My Life'}) SET m.age = 42</sql>
    </changeSet>
</databaseChangeLog>
```
6. I then ran `liquibase [...] update` a last time and it worked fine:
```shell
Liquibase command 'update' was executed successfully.
```

It did not set the attribute `age` since the change set was already ran before and is not marked to be ran when changed. However, the new check sum was taken into account and the validation didn't fail anymore.

**Comment by katadonutskuri** [comment] 2021-12-06 20:35
@fbiville Perhaps I misunderstood the usage of validCheckSum. I thought it could be any value, but it seems you pasted in the new value it spit out. Going by that original assumption of mine, I used a uuid. Basically I wanted a way for liquibase to ignore that validation (e.g because a parameter for `customChange` could be different, modified query, etc), but still use some kind of value to know if a changeset has been ran already.

**Comment by fbiville** [comment] 2021-12-08 08:29
@katadonutskuri the value needs to match a check sum that Liquibase generates for the change set.
When a change set is ran, Liquibase computes a check sum and compares it with the stored check sum and optionally a check sum specified with `<validChecksum />`.

**Closed by fbiville** 2021-12-08 08:29 UTC
Labels: enhancement, Extension Release Candidate :rocket:
