### ISSUE TITLE
Update hangs when statement returns values

### ISSUE THREAD

**Issue by bobmhong** [liquibase/liquibase-neo4j#14] opened 2021-05-11 16:43 UTC
When I run a changeset that returns values, the migration hangs and does not return. 

Here's an example changeset: 
```
<changeSet id="2020-05-11-schedule-pr-closedDate-updater" author="my_name">
  <comment>Schedule repeated call of pr-closedDate-updater</comment>
  <sql>
    CALL apoc.periodic.repeat(
    "pr-closedDate-updater",
    'call apoc.periodic.commit(\'
      MATCH (p:PullRequest) 
      WHERE (not exists(p.closedDate)
        or p.closedDate IS NULL)
      and p.status in ["completed", "abandoned"]
      WITH split(p.id, ".")[1] as prId
      limit 50
      MATCH (r:RestUri {type:"get_pull_request"})
      MATCH (ac:ApiCredential {type:"AZDO_PAT"})
      WITH reduce(r = "", x IN [r.protocol, ac.user, ":", ac.password, "@", r.uri, prId, r.suffix] | r + x) as requestUrl
      CALL apoc.load.jsonParams(requestUrl,{},null)
      YIELD value    
      WITH value.repository.project.id + "." + value.pullRequestId as prUid, value.closedDate as closedDate
      MERGE (pr:PullRequest {id:prUid})
      SET pr.closedDate=closedDate
      RETURN CASE WHEN count(*) &lt; 50 THEN 0 ELSE count(*) END AS count
  \')',600);
  </sql>
</changeSet>
```

I tried adding YIELD name RETURN null to the statment and got the same results.

Any ideas?

Thanks,

Bob

**Comment by fbiville** [comment] 2021-05-12 08:32
Thanks, I actually heard similar feedback with Liquigraph, which also uses the JDBC driver.
It's probably an issue with the latter, I'll investigate.

**Comment by fbiville** [comment] 2021-06-01 08:34
@bobmhong would you have a small dataset to reproduce the issue? Does it happen with an empty DB?

**Comment by fbiville** [comment] 2021-06-11 16:36
I can reproduce the issue, and it seems to be a general with the underlying Neo4j Java Driver. I'll try to see if I can find a solution.

**Comment by fbiville** [comment] 2021-06-11 19:30
@bobmhong it might very well be that your database has a pending lock that prevents a subsequent execution from continuing (it's busy waiting for the lock to disappear before placing its own).
Before re-running the migration, what does `MATCH (lock:`__LiquibaseLock`) RETURN COUNT(lock)` return?

**Comment by fbiville** [comment] 2021-06-21 13:02
@bobmhong are you still facing the problem?

**Comment by katadonutskuri** [comment] 2021-07-21 19:36
I can confirm this is an issue. I had a query return eg `match (c:Foo) return c` and it hung. Then when I changed it to `match (c:Foo) set c.new = 'new'` it worked. Changing it back to a return made it hang again `match (c:Foo) return c limit 2`

I'm on `Liquibase Version: 4.4.1` and `neo4j 4.x`

**Comment by fbiville** [comment] 2021-07-23 09:00
It is likely to be a JDBC driver issue. I will investigate. Thanks y'all for the feedback.

**Comment by fbiville** [comment] 2021-07-23 09:54
I know what the problem is, but not sure what the solution should be.

On the Liquibase side, `liquibase.executor.jvm.JdbcExecutor.ExecuteStatementCallback#doInStatement` gets called for each statement. 
Towards the end, it runs something like this (slightly simplified version here):

```java
        // stmt is a JDBC Statement
        // statement is the "SQL" (here: Cypher) query 
        stmt.execute(statement);
        int updateCount = 0;
        do {
            if (!stmt.getMoreResults()) {
                updateCount = stmt.getUpdateCount();
            }
        } while (updateCount != -1);
```

Now, on the Neo4j JDBC driver side, `org.neo4j.jdbc.bolt.BoltNeo4jStatement#execute` will create a `ResultSet` if it detects a `RETURN` clause in the query (which is the case).

`BoltNeo4jStatement` inherits from `Neo4jStatement` and `org.neo4j.jdbc.Neo4jStatement#getMoreResults()` in particular, which does this:

```java
	@Override public boolean getMoreResults() throws SQLException {
		this.checkClosed();
		return this.currentResultSet != null;
	}
```

Note that `getMoreResults` could also check for `this.currentResultSet.isClosed()` as well, but that does not change the problem: the created `ResultSet` is never consumed and Liquibase's JDBC executor loops forever.

Any idea what the fix should be @nvoxland / @conker84?

**Comment by fbiville** [comment] 2021-07-23 10:11
As pointed out by @conker84, the issue seems to be on the implementation of `getMoreResults`.
Based on the [JavaDoc](https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#getMoreResults()):
> Moves to this Statement object's next result, returns true if it is a ResultSet object, and implicitly closes any current ResultSet object(s) obtained with the method getResultSet. 

Calling `getMoreResults` should change the state of the statement/result set and it currently does not.

**Comment by katadonutskuri** [comment] 2021-07-23 22:07
> As a side note, `RETURN` clauses in migration queries are usually not needed.

This is true, but neo4j APOC functions have return values, which was my original issue. I just used the return queries to confirm.

I saw the merged PR, and tried it out. It seems to be working now, thanks!

**Comment by fbiville** [comment] 2021-07-26 09:33
@katadonutskuri in **theory**, the query you are sharing here should not have any impact, since it has the shape: `CALL procedure()`, **not** `CALL procedure() YIELD ... RETURN ...`

However, the way the JDBC driver detects there is a `RETURN` clause in a query is based on a string match.
In that example, the JDBC driver will erroneously detect a RETURN clause because of the query passed to the APOC procedure. 

The fix that @conker84 pushed to implement `getMoreResults` happens to avoid the problem.
However, the `RETURN` clause detection should be improved and I just opened https://github.com/neo4j-contrib/neo4j-jdbc/issues/272 to that end (so that queries such as the one you just shared won't even get a `ResultSet` needlessly attached to them).

**Comment by fbiville** [comment] 2021-08-04 08:54
Good news, the JDBC driver 4.0.2 has been released yesterday and includes all the fixes.
Not-so-good news: it requires a JDK 11 (my fault actually), whereas this plugin and Liquibase core still have a JDK 8 baseline (see #52). I need to sort this out before creating a new release.

**Comment by fbiville** [comment] 2021-09-09 09:16
JDBC 4.0.3 is now back to JDK 8. This will be merged soon.

**Comment by 25thbamofthetower** [comment] 2021-11-13 00:17
@fbiville I seem to still be getting this problem

```
CALL apoc.periodic.iterate(
        'MATCH (n:SomeLabel) RETURN n',
        'DETACH DELETE n', {batchSize:10000})
```
This seems to hang after finishing deleting 15+ million nodes, each node possibly having 3+ relationships. In the neo4j desktop, the query is no longer listed as running under `call dbms.listQueries()` and the count has reached zero

**Comment by fbiville** [comment] 2021-12-03 16:44
@25thbamofthetower I could not reproduce the issue. I created a large graph with https://neo4j.com/labs/apoc/4.2/overview/apoc.generate/apoc.generate.ba/ against a Neo4j 4.2.5 instance I had running and ran executed Liquibase on:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd">

    <changeSet id="delete-stuff" author="fbiville">
        <comment>Nuke everything</comment>
        <sql>CALL apoc.periodic.iterate(
        'MATCH (n:Person) RETURN n',
        'DETACH DELETE n', {batchSize:10000})
        </sql>
    </changeSet>
</databaseChangeLog>
``` 

What Neo4j server and APOC version are you using? I think it could be an APOC issue instead.

**Comment by fbiville** [comment] 2021-12-17 09:25
Closing this for now as I cannot reproduce the problem.

**Closed by fbiville** 2021-12-17 09:25 UTC
Labels: bug
